bad_words = [
    "very",
    "rather",
    "really",
    "quite",
    "in fact",
    "really",
    "very",
    "that",
    "just",
    "then",
    "totally",
    "Totally",
    "completely",
    "absolutely",
    "literally,",
    "Definitely",
    "certainly",
    "probably",
    "actually",
    "basically",
    "virtually",
    "Rather",
    "quite",
    "somewhat",
    "somehow",
    "pretty",
    "of course",
    "surely",
    "very",
    "feel",
    "finally",
    "frequently",
    "got",
    "just",
    "merely",
    "nearly",
    "need",
    "never",
    'Very',
    'Rather',
    'Really',
    'Quite',
    'In fact',
    'Really',
    'Very',
    'That',
    'Just',
    'Then',
    'Totally',
    'Totally',
    'Completely',
    'Absolutely',
    'Literally',
    'Definitely',
    'Certainly',
    'Probably',
    'Actually',
    'Basically',
    'Virtually',
    'Rather',
    'Quite',
    'Somewhat',
    'Somehow',
    'Pretty',
    'Of course',
    'Surely',
    'Very',
    'Feel',
    'Finally',
    'Frequently',
    'Got',
    'Just',
    'Merely',
    'Nearly',
    'Need',
    'Never',
]


# def create_upper():
#     for i in bad_words:
#         up = i.capitalize()
#         print("'" + up + "'" + ",")


# create_upper()
